POST localhost:8080/api/v1/user/signup
Content-Type: application/json

{
  "email": "rlagudwog@gmail.com",
  "password": "hp12081208!",
  "confirmPassword": "hp12081208!",
  "username": "김형재",
  "nickname": "kimbro97",
  "otp": "136541"
}
