version: '1'
services:
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=user
      - MYSQL_PASSWORD=1234
      - MYSQL_DATABASE=jobfit
    volumes:
      - ./data/mysql/:/var/lib/mysql

networks:
  default:
    driver: bridge
